src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use DateTime;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @Vich\Uploadable
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=true)
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chapeau;

    /**
     * @ORM\Column(type="text", length=30000)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles", fetch="EAGER")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="articles_pictures", fileNameProperty="imageName", size="imageSize")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string")
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     *
     * @var int|null
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ArticleComment", mappedBy="article")
     *
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserLike", mappedBy="likedArticle")
     *
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ArticleVisit", mappedBy="article")
     */
    private $articleVisits;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BookMark", mappedBy="article")
     */
    private $bookMarks;


    /**
     * @ORM\Column(type="datetime", nullable = true)
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Channel", inversedBy="articles")
     */
    private $channel;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\NotificationEvent", mappedBy="article")
     */
    private $notificationEvents;

    /**
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @ORM\Column(name="is_published", type="boolean", nullable=true)
     */
    private $isPublished;


    public function __construct()
    {
        $this->setCreatedAt(new DateTime('now'));
        $this->setUpdatedAt(new DateTime('now'));
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->articleVisits = new ArrayCollection();
        $this->bookMarks = new ArrayCollection();
        $this->notificationEvents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getChapeau()
    {
        return $this->chapeau;
    }

    /**
     * @param mixed $chapeau
     */
    public function setChapeau($chapeau): void
    {
        $this->chapeau = $chapeau;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser(User $writer): self
    {
        //if user didn't wrote anything before or has written articles and is not a writer, he automatically becomes a writer
        if($writer->getNbOfWrittenArticles() == 0 || ($writer->getNbOfWrittenArticles() > 0 && $writer->getIsWriter() == false)) {
            $writer->setIsWriter(true);
        }
        $this->user = $writer;

        return $this;
    }


    public function getCreatedAt(): DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTime $date): self
    {
        $this->createdAt = $date;

        return $this;
    }

    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(DateTime $date): self
    {
        $this->updatedAt = $date;

        return $this;
    }


    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new DateTime();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    /**
     * @return Collection|ArticleComment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(ArticleComment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(ArticleComment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * @return Collection|UserLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(UserLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setLikedArticle($this);
        }

        return $this;
    }

    public function removeLike(UserLike $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            if ($like->getLikedArticle() === $this) {
                $like->setLikedArticle(null);
            }
        }

        return $this;
    }

    public function getIsPublished()
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished)
    {
        $this->isPublished = $isPublished;
    }

    public function getNbOfLikes()
    {
        return count($this->likes);
    }

    public function getNbOfComments()
    {
        return count($this->comments);
    }

    /**
     * @return Collection|ArticleVisit[]
     */
    public function getArticleVisits(): Collection
    {
        return $this->articleVisits;
    }

    public function getNbOfVisits()
    {
        return count($this->articleVisits);
    }

    public function addArticleVisit(ArticleVisit $articleVisit): self
    {
        if (!$this->articleVisits->contains($articleVisit)) {
            $this->articleVisits[] = $articleVisit;
            $articleVisit->setArticle($this);
        }

        return $this;
    }

    public function removeArticleVisit(ArticleVisit $articleVisit): self
    {
        if ($this->articleVisits->contains($articleVisit)) {
            $this->articleVisits->removeElement($articleVisit);
            if ($articleVisit->getArticle() === $this) {
                $articleVisit->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|BookMark[]
     */
    public function getBookMarks(): Collection
    {
        return $this->bookMarks;
    }

    public function addBookMark(BookMark $bookMark): self
    {
        if (!$this->bookMarks->contains($bookMark)) {
            $this->bookMarks[] = $bookMark;
            $bookMark->setArticle($this);
        }

        return $this;
    }

    public function removeBookMark(BookMark $bookMark): self
    {
        if ($this->bookMarks->contains($bookMark)) {
            $this->bookMarks->removeElement($bookMark);
            // set the owning side to null (unless already changed)
            if ($bookMark->getArticle() === $this) {
                $bookMark->setArticle(null);
            }
        }

        return $this;
    }


    public function getChannel(): ?Channel
    {
        return $this->channel;
    }

    public function setChannel(?Channel $channel): self
    {
        $this->channel = $channel;

        return $this;
    }

    /**
     * @return Collection|NotificationEvent[]
     */
    public function getNotificationEvents(): Collection
    {
        return $this->notificationEvents;
    }

    public function addNotificationEvent(NotificationEvent $notificationEvent): self
    {
        if (!$this->notificationEvents->contains($notificationEvent)) {
            $this->notificationEvents[] = $notificationEvent;
            $notificationEvent->setArticle($this);
        }

src/Entity/Notification.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NotificationRepository")
 */
class Notification
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="notifications")
     */
    private $recipient;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $wasRead;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\NotificationEvent", inversedBy="notifications")
     */
    private $notificationEvent;

    public  function  __construct()
    {
        $this->createdAt = new \DateTime('now');
        $this->wasRead = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getWasRead(): ?bool
    {
        return $this->wasRead;
    }

    public function setWasRead(bool $wasRead): self
    {
        $this->wasRead = $wasRead;

        return $this;
    }

    public function getNotificationEvent(): ?NotificationEvent
    {
        return $this->notificationEvent;
    }

    public function setNotificationEvent(?NotificationEvent $notificationEvent): self
    {
        $this->notificationEvent = $notificationEvent;

        return $this;
    }

    public function getContent()
    {
        return $this->getNotificationEvent()->getContent();
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Channel;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Vich\UploaderBundle\Form\Type\VichImageType;


class ArticleType extends AbstractType
{

    private $channelRepository;

    public function __construct(EntityManagerInterface $em)
    {
        $this->channelRepository = $em->getRepository(Channel::class);
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $user = $options['user'];

        $builder
        ->add('title',TextType::class, [
            'label'=> 'Le titre de votre Papier : ',
            'attr' => [
                'placeholder' => 'Votre titre'
            ]
        ])
        ->add('chapeau',TextType::class, [
            'label'=> 'Ajouter un chapeau pour donner envie au lecteur : ',
            'attr' => [
                'placeholder' => 'Votre chapeau'
            ]
        ])
        ->add('description',TextareaType::class, [
            'label'=> 'Par ici le corps de votre papier : ',
            'attr' => [
                'placeholder' => 'Ici'
            ]
        ])
        ->add('imageFile',VichImageType::class, [
            'label'=> 'Associer la photo principale de votre papier : ',
        ]);
        $builder->add('channel',EntityType::class, [
            'label'=> 'Publier votre article dans un de vos channels ? ',
            'class' => Channel::class,
            'placeholder' => '---Choix du channel---',
            'query_builder' => function (EntityRepository $er) use($user){
                return $er->createQueryBuilder('c')
                    ->join('c.channelSubscriptions', 'cs')
                    ->andWhere("cs.user = :user")
                    ->setParameter('user', $user);
            },
        ]);
    }


    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
        $resolver->setRequired('user');
        $resolver->setAllowedTypes('user', User::class);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rédiger un nouvel article : {% endblock %}

{% block body %}
    <div class="coconuts-article-container">
        <h1>Rédiger un nouvel article :</h1>
        {{ include('article//partials/form.html.twig') }}
    </div>
{% endblock %}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <div class ="coconuts-article-container">
        <h1>Modifier l'article : {{article.title}}</h1>

        {{ include('article/partials/form.html.twig', {'button_label': 'Update'}) }}

        <a href="{{ path('article_index') }}">back to list</a>

        {{ include('article/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <div class = "coconuts-article-container">
        <h1>Article index</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>Date de Publication</th>
                    <th>Titre</th>
                    <th>Chapeau</th>
                    <th>Contenu (300 char)</th>
                    <th>Auteur</th>
                    <th>Likes</th>
                    <th>Vues</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for article in articles %}
                <tr>
                    <td>{{ article.createdAt|date("d-M") }}</td>
                    <td>{{ article.title }}</td>
                    <td>{{ article.chapeau }}</td>
                    <td>{{ article.description|striptags|slice(0, 200) }}</td>
                    <td>{{ article.user is not empty ? article.user.username : "utilisateur supprimé"  }}</td>
                    <td>{{ article.nbOfLikes }}</td>
                    <td>{{ article.nbOfComments }}</td>
                    <td>
                        <a href="{{ path('article_show', {'id': article.id}) }}">Détail</a>
                        <a href="{{ path('article_edit', {'id': article.id}) }}">Modifier</a>
                    </td>

                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('article_create') }}">Create new</a>
    </div>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <div class = "coconuts-article-container">
        <div>
            <img class = "coconuts-main-article-picture" src="{{ vich_uploader_asset(article) }}" alt="{{ article.title }}"/>
        </div>
        <br>
        <h1>
            {{ article.title }}
        </h1>
        <h4>
            <span>{{ article.chapeau }}</span>
            <i class="{{ hasBookmark ? "fas" : "far" }} fa-bookmark fa-2x toggle-bookmark-article"
               data-has-bookmark = "{{ hasBookmark == false ? "false" : "true" }}"
               data-article-id = {{ article.id }}>
            </i>
        </h4>
        <div class="row">
            <div class="col-1 ">
                <i class="{{ userHasLiked ? "fas" : "far" }} far fa-heart"></i>
                <span class="dynamic-likes-counter-of-article" data-article_id = "{{ article.id }}">
                    {{article.nbOfLikes}}
                </span>
            </div>
            <div class="col-1 ">
                <i class="fas fa-glasses"></i>
                <span>{{article.nbOfVisits}}</span>
            </div>
            <div class="col-1 ">
                <i class="far fa-comments"></i>
                <span>{{article.nbOfComments}}</span>
            </div>
        </div>
        <div class="row">
            <div class="col-1">
                {% if article.user is not null %}
                    <img src="{{ vich_uploader_asset(article.user) }}"
                         alt="{{ article.user.username }}"
                         class="coconuts-round-picture rikiki-img"
                    />
                {% endif %}
            </div>
            <div class="col-6">
                <div>
                    {% if article.user is not null %}
                        <a href = "{{ path('user_show', {'id': article.user.id}) }}">
                            Par {{ article.user.username }}
                        </a>
                        <a href="javascript:void(0)"
                           class= "coconuts-follow-button coconuts-toggle-follow
                           {{ isFollowing == false ? 'follow' : 'unfollow' }}"
                        >
                            {{ isFollowing == false ? "S\'abonner" : 'Se désabonner'  }}
                        </a>
                    {% else %}
                        <p>Utilisateur supprimé</p>
                    {% endif %}
                </div>
                <div>
                    {{ article.createdAt|date('M-d') }}
                </div>
                {% if article.channel is not null %}
                    <div class="is-secondary">
                        Paru dans :
                        <a href="{{ path('channel_show', {'idChannel' : article.channel.id}) }}">
                            {{ article.channel.title }}
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
        {% if article.isPublished == false %}
            <span class="draft-badge">BROUILLON</span>
        {% endif %}
        <div>{{ article.description }} </div>
        <br>

        <div>
            Vous avez aimé cet article ? Faites-le savoir à son auteur (qui vous aimera d'autant plus fort!)
            <i class="{{ userHasLiked ? "fas" : "far" }} fa-heart fa-3x {{ article.user is not null ? "toggle-like-article" : ""}}"
               data-article-id = "{{ article.id }}"
               data-has-liked = "{{ userHasLiked == false ? "false" : "true" }}">
            </i>
            <span class="dynamic-likes-counter-of-article" data-article-id = "{{ article.id }}">
                {{article.nbOfLikes}}
            </span>
        </div>
        {% if article.user is not null %}
            {{ render(controller(
                'App\\Controller\\WriterController::displayPartialWriterResumeBlock',
                { 'idWriter': article.user.id }
            )) }}
        {% endif %}
        <!-- BLOC AUTEUR -->
        <input id="visitorId" name="visitorId" type="hidden" value="{{ app.user is null ? "" : app.user.id }}">
        <input id="articleId" name="articleId" type="hidden" value="{{ article.id }}">
        <input id="writerId" name="writerId" type="hidden" value="{{ article.user is not null ? article.user.id : ""}}">
        <input id="isFollowing" name="isFollowing" type="hidden" value="{{ isFollowing == false ? 0 : 1}}">

        <div id="comment-list">
            <div>Commentaires : </div>
            <ul class="coconuts-comment-section">
                <li id = "jquery-hidden-comment-block" class="comment" data-id = "">
                    <div class="comment-info">
                        <a class="comment-username" href="">
                        </a>
                        <span class="comment-date">A l'instant</span>
                    </div>
                    <a class="comment-avatar" href="#">
                        <img class="coconuts-round-picture rikiki-img user-picture"
                             src=""
                             width="35" alt="Profile Avatar" title=""
                        />
                    </a>
                    <p class="comment-body"></p>
                    <i class="fas fa-trash-alt delete-comment-action"></i>
                </li>
                {% if comments is not empty %}
                    {% for comment in comments %}
                        {% if comment.author is not null %}
                            <li class= "comment {{ article.user is not null ? (comment.author.id == article.user.id ? "author-comment" : "user-comment") : "user-comment" }}"
                                data-id = "{{ comment.id }}">
                                <div class="comment-info">
                                    <a class="comment-username" href="{{ path('user_show', {id : comment.author.id}) }}">
                                        {{ comment.author.username }}
                                    </a>
                                    <span class="comment-date">{{ date_calculator.convertToAdaptedDuration(comment.createdAt)}}</span>
                                </div>
                                <a class="comment-avatar" href="{{ path('user_show', {id : comment.author.id}) }}">
                                    <img class="coconuts-round-picture rikiki-img"
                                         src="{{ vich_uploader_asset(comment.author) }}"
                                         width="35" alt="Profile Avatar" title="{{ comment.author.username }}"
                                    />
                                </a>
                                <p class="comment-body">{{ comment.content }}</p>
                                {% if app.user is not null %}
                                    {% if app.user.isAdmin or app.user.id == comment.author.id %}
                                        <i class="fas fa-trash-alt delete-comment-action" data-id=" {{ comment.id }}"></i>
                                    {% endif %}
                                {% endif %}
                            </li>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <li id="no-commentary">Pas de commentaires à ce jour : </li>
                {% endif %}
                {% if app.user is not null  %}
                    <li class="write-new">
                        <div class="is-row">
                            <div>
                                <label for = "send-comment-input"></label>
                                <textarea name ="send-comment-input"
                                          id="send-comment-input"
                                          class="textarea-stylay"
                                >Entrez un commentaire
                                </textarea>
                                <div>
                                    <button id="send-comment-action">Envoyer</button>
                                </div>
                            </div>
                            <a href="{{ path('user_show', {id : app.user.id}) }}">
                                <img class="coconuts-round-picture rikiki-img" id="visitor-picture"
                                     src="{{ vich_uploader_asset(app.user) }}" data-href="{{ path('user_show', {id : app.user.id} ) }}"
                                     width="35" alt="Profile Avatar" title="{{ app.user.username }}"
                                />
                            </a>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>

        {% if app.user is not null and article.user is not null %}
            {% if app.user.id == article.user.id %}
                <a href="{{ path('article_edit', {'id': article.id}) }}">Modifier votre article</a>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}