src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use DateTime;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @Vich\Uploadable
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=true)
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chapeau;

    /**
     * @ORM\Column(type="text", length=30000)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles", fetch="EAGER")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="articles_pictures", fileNameProperty="imageName", size="imageSize")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string")
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     *
     * @var int|null
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ArticleComment", mappedBy="article")
     *
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserLike", mappedBy="likedArticle")
     *
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ArticleVisit", mappedBy="article")
     */
    private $articleVisits;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BookMark", mappedBy="article")
     */
    private $bookMarks;


    /**
     * @ORM\Column(type="datetime", nullable = true)
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Channel", inversedBy="articles")
     */
    private $channel;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\NotificationEvent", mappedBy="article")
     */
    private $notificationEvents;

    /**
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @ORM\Column(name="is_published", type="boolean", nullable=true)
     */
    private $isPublished;


    public function __construct()
    {
        $this->setCreatedAt(new DateTime('now'));
        $this->setUpdatedAt(new DateTime('now'));
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->articleVisits = new ArrayCollection();
        $this->bookMarks = new ArrayCollection();
        $this->notificationEvents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getChapeau()
    {
        return $this->chapeau;
    }

    /**
     * @param mixed $chapeau
     */
    public function setChapeau($chapeau): void
    {
        $this->chapeau = $chapeau;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser(User $writer): self
    {
        //if user didn't wrote anything before or has written articles and is not a writer, he automatically becomes a writer
        if($writer->getNbOfWrittenArticles() == 0 || ($writer->getNbOfWrittenArticles() > 0 && $writer->getIsWriter() == false)) {
            $writer->setIsWriter(true);
        }
        $this->user = $writer;

        return $this;
    }


    public function getCreatedAt(): DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTime $date): self
    {
        $this->createdAt = $date;

        return $this;
    }

    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(DateTime $date): self
    {
        $this->updatedAt = $date;

        return $this;
    }


    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new DateTime();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    /**
     * @return Collection|ArticleComment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(ArticleComment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(ArticleComment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * @return Collection|UserLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(UserLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setLikedArticle($this);
        }

        return $this;
    }

    public function removeLike(UserLike $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            if ($like->getLikedArticle() === $this) {
                $like->setLikedArticle(null);
            }
        }

        return $this;
    }

    public function getIsPublished()
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished)
    {
        $this->isPublished = $isPublished;
    }

    public function getNbOfLikes()
    {
        return count($this->likes);
    }

    public function getNbOfComments()
    {
        return count($this->comments);
    }

    /**
     * @return Collection|ArticleVisit[]
     */
    public function getArticleVisits(): Collection
    {
        return $this->articleVisits;
    }

    public function getNbOfVisits()
    {
        return count($this->articleVisits);
    }

    public function addArticleVisit(ArticleVisit $articleVisit): self
    {
        if (!$this->articleVisits->contains($articleVisit)) {
            $this->articleVisits[] = $articleVisit;
            $articleVisit->setArticle($this);
        }

        return $this;
    }

    public function removeArticleVisit(ArticleVisit $articleVisit): self
    {
        if ($this->articleVisits->contains($articleVisit)) {
            $this->articleVisits->removeElement($articleVisit);
            if ($articleVisit->getArticle() === $this) {
                $articleVisit->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|BookMark[]
     */
    public function getBookMarks(): Collection
    {
        return $this->bookMarks;
    }

    public function addBookMark(BookMark $bookMark): self
    {
        if (!$this->bookMarks->contains($bookMark)) {
            $this->bookMarks[] = $bookMark;
            $bookMark->setArticle($this);
        }

        return $this;
    }

    public function removeBookMark(BookMark $bookMark): self
    {
        if ($this->bookMarks->contains($bookMark)) {
            $this->bookMarks->removeElement($bookMark);
            // set the owning side to null (unless already changed)
            if ($bookMark->getArticle() === $this) {
                $bookMark->setArticle(null);
            }
        }

        return $this;
    }


    public function getChannel(): ?Channel
    {
        return $this->channel;
    }

    public function setChannel(?Channel $channel): self
    {
        $this->channel = $channel;

        return $this;
    }

    /**
     * @return Collection|NotificationEvent[]
     */
    public function getNotificationEvents(): Collection
    {
        return $this->notificationEvents;
    }

    public function addNotificationEvent(NotificationEvent $notificationEvent): self
    {
        if (!$this->notificationEvents->contains($notificationEvent)) {
            $this->notificationEvents[] = $notificationEvent;
            $notificationEvent->setArticle($this);
        }

src/Entity/Channel.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ChannelRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=true)
 */
class Channel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ChannelSubscription", mappedBy="channel")
     */
    private $channelSubscriptions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="channel")
     */
    private $articles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ChannelSubscriptionRequest", mappedBy="channel")
     */
    private $channelSubscriptionRequests;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\NotificationEvent", mappedBy="channel")
     */
    private $notificationEvents;

    /**
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    private $deletedAt;


    public function __construct()
    {
        $this->channelSubscriptions = new ArrayCollection();
        $this->articles = new ArrayCollection();
        $this->channelSubscriptionRequests = new ArrayCollection();
        $this->notificationEvents = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|ChannelSubscription[]
     */
    public function getChannelSubscriptions(): Collection
    {
        return $this->channelSubscriptions;
    }

    public function addChannelSubscription(ChannelSubscription $channelSubscription): self
    {
        if (!$this->channelSubscriptions->contains($channelSubscription)) {
            $this->channelSubscriptions[] = $channelSubscription;
            $channelSubscription->setChannel($this);
        }

        return $this;
    }

    public function removeChannelSubscription(ChannelSubscription $channelSubscription): self
    {
        if ($this->channelSubscriptions->contains($channelSubscription)) {
            $this->channelSubscriptions->removeElement($channelSubscription);
            if ($channelSubscription->getChannel() === $this) {
                $channelSubscription->setChannel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setChannel($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getChannel() === $this) {
                $article->setChannel(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection|ChannelSubscriptionRequest[]
     */
    public function getChannelSubscriptionRequests(): Collection
    {
        return $this->channelSubscriptionRequests;
    }

    public function addChannelSubscriptionRequest(ChannelSubscriptionRequest $channelSubscriptionRequest): self
    {
        if (!$this->channelSubscriptionRequests->contains($channelSubscriptionRequest)) {
            $this->channelSubscriptionRequests[] = $channelSubscriptionRequest;
            $channelSubscriptionRequest->setChannel($this);
        }

        return $this;
    }

    public function removeChannelSubscriptionRequest(ChannelSubscriptionRequest $channelSubscriptionRequest): self
    {
        if ($this->channelSubscriptionRequests->contains($channelSubscriptionRequest)) {
            $this->channelSubscriptionRequests->removeElement($channelSubscriptionRequest);
            // set the owning side to null (unless already changed)
            if ($channelSubscriptionRequest->getChannel() === $this) {
                $channelSubscriptionRequest->setChannel(null);
            }
        }

        return $this;
    }

    public function getNbOfArticles()
    {
        return count($this->articles);
    }

    public function getNbOfChannelSubscriptions()
    {
        return count($this->channelSubscriptions);
    }


    public function getAdminUsers()
    {
        $tab = [];

        foreach ($this->channelSubscriptions as $channelSubscription) {
            if ($channelSubscription->getIsAdmin()) {
                $tab[] = $channelSubscription->getUser();
            }
        }

        return $tab;
    }

    /**
     * @return Collection|NotificationEvent[]
     */
    public function getNotificationEvents(): Collection
    {
        return $this->notificationEvents;
    }

    public function addNotificationEvent(NotificationEvent $notificationEvent): self
    {
        if (!$this->notificationEvents->contains($notificationEvent)) {
            $this->notificationEvents[] = $notificationEvent;
            $notificationEvent->setChannel($this);
        }

        return $this;
    }

    public function removeNotificationEvent(NotificationEvent $notificationEvent): self
    {
        if ($this->notificationEvents->contains($notificationEvent)) {
            $this->notificationEvents->removeElement($notificationEvent);
            // set the owning side to null (unless already changed)
            if ($notificationEvent->getChannel() === $this) {
                $notificationEvent->setChannel(null);
            }
        }

        return $this;
    }

    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <div class="coconuts-article-container">
        <h1>Edit User</h1>

        {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

        <a href="{{ path('user_index') }}">back to list</a>

        {{ include('user/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <div class="coconuts-article-container">
        <h1>Users index</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Profile Description</th>
                    <th>IsAdmin</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.profileDescription }}</td>
                    <td>{{ user.isAdmin ? 'Yes' : 'No' }}</td>
                    <td>
                        <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                        <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="10">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('register_as_new_member') }}">Create new</a>
    </div>
{% endblock %}


{% block javascripts %}
     {{ parent() }}
     {{ encore_entry_script_tags('toggleArticleLike') }}
{% endblock %}

templates/user/register_as_new_member.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}
    <div class = "coconuts-article-container">
        <h1>Devenez un nouveau membre</h1>

        {{ include('user/partial/form.html.twig') }}

        <a href="{{ path('public_home_page') }}">HomePage</a>
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ user.username }} {% endblock %}

{% block body %}
    <div class ="coconuts-story-container">
        <div class ="block-user-profile border-stylay ">
            <div class="is-row">
                <div>
                    <p class="is-title">
                        {{ user.username }} {{ render_author_badge(user.hasWritten) }}
                        <a href="javascript:void(0)"
                           class= "coconuts-follow-button coconuts-toggle-follow
                                {{ isFollowing == false ? 'follow' : 'unfollow' }}"
                        >
                            {{ isFollowing == false ? "S\'abonner" : 'Se désabonner'  }}
                        </a>
                    </p>
                    <p>{{ user.profileDescription }}</p>
                </div>
                <div>
                    <img src="{{ vich_uploader_asset(user) }}"
                         alt="{{ user.username }}"
                         class="coconuts-round-picture small-img"
                    />
                </div>
            </div>
            <div>
                <p class="is-secondary">Membre Coconuts depuis le {{user.createdAt|date("m/d/Y")}}</p>
                <p class="is-secondary">{{user.nbOfSubscribedFollows}} Abonnements {{user.nbOfIncomingFollows}} Abonnés {{user.nbOfArticles}} Articles </p>
            </div>
        </div>

        <div class="">
            <button class="tab-button coconuts-active" id="articles" data-type="user-profile">Articles</button>
            <button class="tab-button coconuts-inactive" id="commentaires" data-type="user-profile" >Commentaires</button>
            <button class="tab-button coconuts-inactive" id="likes" data-type="user-profile">Likes</button>
            <button class="tab-button coconuts-inactive" id="channels" data-type="user-profile">Chaines</button>
            <button class="tab-button coconuts-inactive" id="writers" data-type="user-profile">Abonnements</button>
        </div>

        <hr>

        <div id="articles" data-type="user-profile">
            {% if articles is not null %}
                {% for article in articles %}
                    {% set hasBookmark = status_generator.getHasBookmarkStatus(article, app.user) %}
                    {% set hasLiked = status_generator.getHasLikedArticleStatus(article, app.user) %}
                    {% include "/article/partials/article_medium_size_block.html.twig" with {
                        "article" : article,
                        "hasLiked" : hasLiked,
                        "hasBookmark" : hasBookmark,
                    } %}
                {% endfor %}
            {% else %}
                <div class="border-stylay ">
                    Pas d'article pour ce membre.
                </div>
            {% endif %}
        </div>


        <div id="commentaires"  class="coconuts-hide" data-type="user-profile">
            {% if publishedComments is not empty %}
                {% for comment in publishedComments %}
                    {% set hasBookmark = false %}
                    {#
                        Cette partie est réservée aux futurs marques-page de commentaires.
                        Pour peu que l'on crée cette jointure dès lors, il faudra ajouter un js
                        dédié différent du marques-page article
                        {% if app.user is not null %}
                            {% if app.user.hasBookmarkedArticle(comment) == true %}
                                {% set hasBookmark = true %}
                            {% endif %}
                        {% endif %}
                    #}
                    <div class="border-stylay ">
                        <div class="story-article-header is-row">
                            <img src ="{{ vich_uploader_asset(comment.author) }}"
                                 alt="{{ comment.author.username }}"
                                 class ="coconuts-round-picture rikiki-img"
                            >
                            <div>
                                <a href="{{ path('user_show', {'id': comment.author.id})}}">
                                    <p class="is-title">{{comment.author.username}}</p>
                                </a>
                                <p class="is-secondary">{{comment.createdAt|date("d-m-Y")}} - XX minutes read</p>
                            </div>
                        </div>
                        <div class="story-comment-body border-stylay ">
                            <a href="{{ path('article_show', {'id': comment.article.id})}}">
                                <p class="is-title">{{comment.article.title}}</p>
                            </a>
                            <a href="{{ path('article_show', {'id': comment.article.id})}}">
                                <p class="is-secondary"> {{ comment.article.user is not null ?  comment.article.user.username : "utilisateur supprimé" }} </p>
                            </a>

                        </div>
                        <div class="story-article-footer">
                            <p class="">{{comment.content}}</p>
                            <div class="story-article-footer">
                                <i class="far fa-heart toggle-like-article fa-2x"></i>
                                <span class="dynamic-likes-counter-of-comment" data-comment-id = "{{ comment.id }}">
                                        {{comment.nbOfLikes}}
                                    </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="border-stylay ">
                    Aucun commentaire pour ce membre.
                </div>
            {% endif %}
        </div>

        <div id="likes" class = "coconuts-hide" data-type="user-profile">
            {% if likedArticles is not empty %}
                {% for article in likedArticles %}
                    {% set hasBookmark = status_generator.getHasBookmarkStatus(article, app.user) %}
                    {% set hasLiked = status_generator.getHasLikedArticleStatus(article, app.user) %}
                    {% include "/article/partials/article_medium_size_block.html.twig" with {
                        "article" : article,
                        "hasLiked" : hasLiked,
                        "hasBookmark" : hasBookmark,
                    } %}

                {% endfor %}
            {% else %}
                <div class="border-stylay ">
                    Aucun like pour ce membre.
                </div>
            {% endif %}
        </div>

        <div id="channels" class="coconuts-hide" data-type="user-profile" >
            {% if channels is not empty %}
                {% for channel in channels %}
                    <div class="small-border-stylay ">
                        <a href="{{ path('channel_show', {'idChannel' : channel.id}) }}">
                            <h4>{{ channel.title }}</h4>
                        </a>
                        <div class="chapeau">{{ channel.description }}</div>
                        <div class="secondary-info">
                            {{ channel.getNbOfArticles }} articles
                            {{ channel.getNbOfChannelSubscriptions }} abonnés
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div>Aucun channel</div>
            {% endif %}
        </div>

        <div id="writers" class = "coconuts-hide" data-type="user-profile" >
            {% if followedWriters is not empty %}
                {% for writer in followedWriters %}
                    {% include '/user/partial/user_wih_articles_short_table_item.html.twig' with {'user' : writer, 'createdAt': writer.createdAt} %}
                {% endfor %}
            {% else %}
                <div>Aucun follow</div>
            {% endif %}
        </div>

        <input id="visitorId" name="visitorId" type="hidden" value="{{ app.user is null ? "" : app.user.id }}">
        <input id="writerId" name="writerId" type="hidden" value="{{ user.id}}">
        <input id="isFollowing" name="isFollowing" type="hidden" value="{{ isFollowing == false ? 0 : 1}}">
    </div>
{% endblock %}